# Generated by Django 5.0.3 on 2025-03-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('politics', 'Politics'), ('entertainment', 'Entertainment'), ('technology', 'Technology'), ('business', 'Business'), ('world', 'World')], max_length=20)),
                ('video_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
