# Generated by Django 5.0.3 on 2025-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
