# Generated by Django 5.0.3 on 2025-04-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_post_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='affilate_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
